#module info
module: default
runtime: nodejs
vm: true
skip_files:
  - ^(.*/)?.*/node_modules/.*$

#manual scaling
manual_scaling:
  instances: 1

#vmsettings
vm_settings:
  machine_type: f1-micro

#netwotrk
network:
  forwarded_ports:
    - 8081